pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_MISSING: &str = "IFCCAD_PACKAGE_ENTRYPOINT_MISSING";
pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_INVALID: &str = "IFCCAD_PACKAGE_ENTRYPOINT_INVALID";
pub(crate) const IFCCAD_PACKAGE_JSON_INVALID: &str = "IFCCAD_PACKAGE_JSON_INVALID";
pub(crate) const IFCCAD_PACKAGE_PATH_INVALID: &str = "IFCCAD_PACKAGE_PATH_INVALID";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_MISSING: &str = "IFCCAD_PACKAGE_RESOURCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED: &str =
    "IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED";
pub(crate) const IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED: &str = "IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED";
