pub(crate) const IFCCAD_PACKAGE_CHECKSUM_MISMATCH: &str = "IFCCAD_PACKAGE_CHECKSUM_MISMATCH";
pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_MISSING: &str = "IFCCAD_PACKAGE_ENTRYPOINT_MISSING";
pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_INVALID: &str = "IFCCAD_PACKAGE_ENTRYPOINT_INVALID";
pub(crate) const IFCCAD_PACKAGE_JSON_INVALID: &str = "IFCCAD_PACKAGE_JSON_INVALID";
pub(crate) const IFCCAD_PACKAGE_NODE_PATH_DUPLICATE: &str = "IFCCAD_PACKAGE_NODE_PATH_DUPLICATE";
pub(crate) const IFCCAD_PACKAGE_NODE_REFERENCE_MISSING: &str =
    "IFCCAD_PACKAGE_NODE_REFERENCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_NODE_REFERENCE_TYPE_MISMATCH: &str =
    "IFCCAD_PACKAGE_NODE_REFERENCE_TYPE_MISMATCH";
pub(crate) const IFCCAD_PACKAGE_PATH_INVALID: &str = "IFCCAD_PACKAGE_PATH_INVALID";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_MISSING: &str = "IFCCAD_PACKAGE_RESOURCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_SCHEMA_INVALID: &str = "IFCCAD_PACKAGE_SCHEMA_INVALID";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED: &str =
    "IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED";
pub(crate) const IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED: &str = "IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED";
pub(crate) const IFCCAD_PACKAGE_BINDING_INVALID: &str = "IFCCAD_PACKAGE_BINDING_INVALID";
pub(crate) const IFCCAD_PACKAGE_APPEARANCE_INVALID: &str = "IFCCAD_PACKAGE_APPEARANCE_INVALID";
pub(crate) const IFCCAD_PACKAGE_LAYER_NAME_DUPLICATE: &str = "IFCCAD_PACKAGE_LAYER_NAME_DUPLICATE";
pub(crate) const IFCCAD_IFCDR_VERSION_UNSUPPORTED: &str = "IFCCAD_IFCDR_VERSION_UNSUPPORTED";
pub(crate) const IFCCAD_IFCDR_STRUCTURE_INVALID: &str = "IFCCAD_IFCDR_STRUCTURE_INVALID";
pub(crate) const IFCCAD_IFCDR_DIRECTORY_INVALID: &str = "IFCCAD_IFCDR_DIRECTORY_INVALID";
pub(crate) const IFCCAD_IFCDR_REFERENCE_MISSING: &str = "IFCCAD_IFCDR_REFERENCE_MISSING";
pub(crate) const IFCCAD_IFCDR_ENTITY_ID_DUPLICATE: &str = "IFCCAD_IFCDR_ENTITY_ID_DUPLICATE";
pub(crate) const IFCCAD_IFCDR_ENTITY_ORDER_INVALID: &str = "IFCCAD_IFCDR_ENTITY_ORDER_INVALID";
pub(crate) const IFCCAD_IFCDR_STREAM_SCHEMA_UNSUPPORTED: &str =
    "IFCCAD_IFCDR_STREAM_SCHEMA_UNSUPPORTED";
