pub(crate) const IFCCAD_IFCDR_VERSION_UNSUPPORTED: &str = "IFCCAD_IFCDR_VERSION_UNSUPPORTED";
pub(crate) const IFCCAD_IFCDR_UNIT_UNSUPPORTED: &str = "IFCCAD_IFCDR_UNIT_UNSUPPORTED";
pub(crate) const IFCCAD_IFCDR_STRUCTURE_INVALID: &str = "IFCCAD_IFCDR_STRUCTURE_INVALID";
pub(crate) const IFCCAD_IFCDR_DIRECTORY_INVALID: &str = "IFCCAD_IFCDR_DIRECTORY_INVALID";
pub(crate) const IFCCAD_IFCDR_REFERENCE_MISSING: &str = "IFCCAD_IFCDR_REFERENCE_MISSING";
pub(crate) const IFCCAD_IFCDR_ENTITY_ID_DUPLICATE: &str = "IFCCAD_IFCDR_ENTITY_ID_DUPLICATE";
pub(crate) const IFCCAD_IFCDR_ENTITY_ORDER_INVALID: &str = "IFCCAD_IFCDR_ENTITY_ORDER_INVALID";
pub(crate) const IFCCAD_IFCDR_STREAM_SCHEMA_UNSUPPORTED: &str =
    "IFCCAD_IFCDR_STREAM_SCHEMA_UNSUPPORTED";
