import {createFileClient,decodeBase64} from './browser-client.mjs';
import {initializeCadPreview} from './cad-preview.mjs';
import {initializeWorkspace} from './workspace.mjs';
import {conversionOptions} from './conversion-settings.mjs';
import {examples} from './examples.mjs';
import {cadOutputForSource,supportsCadVersion} from './cad-formats.mjs';
const $=id=>document.getElementById(id),client=createFileClient();let source,controller,generation=0,stale=false,result,sourceCadVersion;
function showsCad(tab){return tab==='overview'||tab==='drawing';}
const workspace=initializeWorkspace({onTab:tab=>{if(showsCad(tab)&&!stale)preview.show();else preview.hide();},onSelection:key=>{if(!stale&&drawingFormat()==='ifccad')void preview.selectElement(key);},onPreferences:()=>{preview.refresh?.();updateInputControls();updatePreservation();updateTolerance();updateCadSourceNote();}}),t=(key,values)=>workspace.t(key,values),preview=initializeCadPreview({translate:t,onReport:value=>workspace.setCadReport(value),onState:value=>workspace.setCadStatus(value),externalSettings:true});
function showStatus(message,quiet=false){workspace.setMessage?.(message,quiet);$("status").textContent=message;$("status").hidden=quiet;}
function drawingFormat(){return source?.kind==='ifccad'?'ifccad':source?.kind==='drawing'?'ocdraw':source?.drawingFormat||'ifccad';}
function selectedOptions(){return conversionOptions({mode:$('tolerance-mode').value||'default',value:$('tolerance-value').value,unit:$('tolerance-unit').value||'mm'});}
function updateInputControls(){const format=$('file').files?.[0]?.name.match(/\.(dwg|dxf)$/i)?.[1]?.toUpperCase();$('drawing-format-control').hidden=!format;$('drawing-format-label').textContent=format?t('convertTo',{format}):'';$('drawing-format').disabled=!format||!!controller;}
function updatePreservation(){const cad=/\.(dxf|dwg)$/i.test($('file').files?.[0]?.name||'');const available=cad&&$('drawing-format').value==='ocdraw';$('preservation-control').hidden=!available;$('preserve-splines').disabled=!available||!!controller;}
function updateCadSourceNote(){const label=t('downloadCadOutput',{format:($('preview-format').value||'dxf').toUpperCase(),version:$('preview-version').value||'AC1032'});$('cad-download').title=label;$('cad-download').ariaLabel=label;const unmatched=source?.kind==='cad'&&sourceCadVersion&&!supportsCadVersion(sourceCadVersion);$('cad-source-settings-note').hidden=!unmatched;$('cad-source-settings-note').textContent=unmatched?t('unsupportedSourceCadVersion',{sourceVersion:sourceCadVersion,outputVersion:$('preview-version').value}):'';}
function updateTolerance(){const mode=$('tolerance-mode').value||'default';$('custom-tolerance').hidden=mode!=='custom';const unit=result?.presentation?.unit||result?.presentation?.graph?.data?.find(n=>n.attributes?.['ifccad::drawing'])?.attributes['ifccad::drawing'].lengthUnit,capable=result?.conversionCapabilities?.[drawingFormat()]?.adjustableTolerance;for(const option of Array.from($('tolerance-mode').options||[]))if(option.value!=='default')option.disabled=capable===false;if($('tolerance-mode').options?.[0])$('tolerance-mode').options[0].textContent=t(capable===false?'legacyTolerance':'defaultTolerance');$('tolerance-effective').textContent=(unit?t('unitLabel',{unit}):'')+(capable===false?' · '+t('toleranceUnavailable'):'');}
function finishBusy(){controller=null;workspace.clearLoading();$('file').disabled=false;$('open').disabled=false;$('cancel').disabled=true;updateInputControls();updatePreservation();}
function loadingInfo(name,kind,operation){return {name,action:operation?'exportingTo':kind==='cad'?'convertingTo':'openingFile',format:operation?.format?.toUpperCase()||($('drawing-format').value==='ocdraw'?'OCDraw':'IFCCAD')};}
function clearSelection(){generation++;controller?.abort();finishBusy();source=undefined;result=undefined;sourceCadVersion=undefined;stale=false;preview.clear();workspace.clear();updateCadSourceNote();$('export').disabled=true;$('cad-download').disabled=true;$('drawing').hidden=true;}
function show(value,operation){if(operation){if(['dxf','dwg'].includes(operation.format))workspace.setCadReport(value);$('export').disabled=!result?.validation?.strictAvailable||stale;$('cad-download').disabled=$('export').disabled;showStatus(value.failure?.message||t('ready'),!value.failure);return;}result=value;const label=drawingFormat()==='ifccad'?'IFCCAD':'OCDraw';$('content-title').textContent=label+'-'+t('contents').toLowerCase();$('export').title=t('downloadNative',{format:label});$('export').ariaLabel=$('export').title;$('drawing').hidden=!value.presentation&&!value.nativeSourceText;$('name').textContent=value.source?.name||source.name;
 workspace.show({...value,inspectedFormat:drawingFormat(),presentation:value.presentation?{...value.presentation,format:drawingFormat()}:null},value.nativeSourceText||'');
 $('export').disabled=!value.validation?.strictAvailable||stale;$('cad-download').disabled=$('export').disabled;$('preview-open').disabled=$('export').disabled&&source?.kind!=='cad';showStatus(value.failure?.message||t(value.validation?.strictAvailable?(value.presentation?.opaqueEntityCount>0?'readyOpaque':'ready'):'invalid'),!!value.validation?.strictAvailable&&!value.failure&&!(value.presentation?.opaqueEntityCount>0));updateTolerance();
}
function download(file){const url=URL.createObjectURL(new Blob([decodeBase64(file.base64)])),link=document.createElement('a');link.href=url;link.download=file.fileName||source.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function run(operation,{newSource=false}={}){if(!source)return;const current=++generation;controller=new AbortController();$('file').disabled=true;$('open').disabled=true;$('cancel').disabled=false;$('export').disabled=true;$('cad-download').disabled=true;$('drawing-format').disabled=true;
 workspace.setLoading({...loadingInfo(source.name,source.kind,operation),phase:'preparing'});
 try{const value=await client.open({...source,...(operation?{export:operation}:{})},{signal:controller.signal,onProgress:phase=>{if(current===generation){workspace.setStatus(phase);workspace.setLoading({phase});}}});if(current!==generation)return;if(newSource&&source.kind==='cad'){sourceCadVersion=value.reader?.version;const output=cadOutputForSource(source.name,sourceCadVersion,{format:$('preview-format').value,version:$('preview-version').value});$('preview-format').value=output.format;$('preview-version').value=output.version;}stale=false;show(value,operation);updateCadSourceNote();
  if(!operation){if(newSource)preview.setSource({...source},!!value.validation?.strictAvailable&&!value.failure);else preview.updateSource({...source},!!value.validation?.strictAvailable&&!value.failure);if(value.validation?.strictAvailable&&!value.failure)void preview.select({format:$('preview-format').value||'dxf',version:$('preview-version').value||'AC1032'});}
  if(operation&&value.export?.download&&!value.failure)download(value.export.download);
 }catch(e){if(current===generation){showStatus(e.name==='AbortError'?t('cancelled'):e.message);if(operation&&e.name!=='AbortError')show({failure:{message:e.message}},operation);if(!operation&&e.name!=='AbortError')preview.setSource({...source},false);}}
 finally{if(current===generation)finishBusy();}
}
async function openFile(file){clearSelection();const readingGeneration=generation;updateInputControls();if(!file){workspace.setStatus('chooseFirst');return;}if(file.size>64*1024*1024){workspace.setStatus('tooLarge');return;}const kind=/\.(dxf|dwg)$/i.test(file.name)?'cad':/\.ifcx(?:\.json)?$/i.test(file.name)?'ifccad':'drawing';$('file').disabled=true;$('open').disabled=true;$('cancel').disabled=false;workspace.setStatus('loading');workspace.setLoading({...loadingInfo(file.name,kind),phase:'loading'});
 try{const options=selectedOptions(),bytes=await file.arrayBuffer();if(readingGeneration!==generation)return;source={kind,name:file.name,...(kind==='cad'?{drawingFormat:$('drawing-format').value||'ifccad',preserveSplines:$('preserve-splines').checked===true&&$('drawing-format').value==='ocdraw'}:{}),conversionOptions:options,files:[{path:file.name,bytes}]};}
 catch(e){if(readingGeneration===generation){showStatus(t('readFailed')+' '+e.message);finishBusy();}return;}
 const openedGeneration=generation+1;await run(undefined,{newSource:true});if(generation!==openedGeneration)return false;if(showsCad(workspace.state?.tab)&&(result?.validation?.strictAvailable||source?.kind==='cad'))void preview.show();return true;
}
$('file').onchange=()=>{clearSelection();if(/\.(dxf|dwg)$/i.test($('file').files?.[0]?.name||''))$('preserve-splines').checked=true;updateInputControls();updatePreservation();};$('open').onclick=()=>openFile($('file').files[0]);
function settingsChanged(){updatePreservation();stale=!!source;if(stale){preview.cancel();workspace.setStatus('stale');$('export').disabled=true;$('cad-download').disabled=true;$('preview-open').disabled=true;}updateInputControls();updatePreservation();updateTolerance();updateCadSourceNote();}
$('drawing-format').onchange=settingsChanged;
for(const name of ['tolerance-mode','tolerance-value','tolerance-unit','preview-format','preview-version','preserve-splines'])$(name).onchange=settingsChanged;
$('apply-settings').onclick=async()=>{let options;try{options=selectedOptions();}catch(e){showStatus(e.message);return;}if(!source)return;source={...source,conversionOptions:options,...(source.kind==='cad'?{drawingFormat:$('drawing-format').value||'ifccad',preserveSplines:$('preserve-splines').checked===true&&$('drawing-format').value==='ocdraw'}:{})};await run();await preview.select({format:$('preview-format').value,version:$('preview-version').value,conversionOptions:options});if(showsCad(workspace.state?.tab)&&!stale&&(result?.validation?.strictAvailable||source?.kind==='cad'))void preview.show();};
$('export').onclick=()=>stale?undefined:run({format:drawingFormat()});$('cad-download').onclick=()=>stale?undefined:run({format:$('preview-format').value,version:$('preview-version').value});
function cancel(){generation++;controller?.abort();finishBusy();workspace.setStatus('cancelled');}
$('cancel').onclick=cancel;$('loading-cancel').onclick=cancel;
$('preview-open').onclick=()=>{if(!stale)workspace.selectTab('drawing');};
for(const example of examples){const option=document.createElement('option');option.value=example.path;option.textContent=example.format+' · '+example.name;$('examples').append(option);}
async function openExample(path){const example=examples.find(x=>x.path===path);if(!example)return;clearSelection();const loadingGeneration=generation;controller=new AbortController();$('file').disabled=true;$('open').disabled=true;$('cancel').disabled=false;workspace.setLoading({...loadingInfo(example.path.split('/').at(-1),example.format==='IFCCAD'?'ifccad':'drawing'),phase:'loading'});try{const response=await fetch(example.path,{signal:controller.signal});if(!response.ok)throw Error('Example unavailable');const bytes=await response.arrayBuffer();if(loadingGeneration!==generation)return;$('file').value='';if(await openFile({name:example.path.split('/').at(-1),size:bytes.byteLength,arrayBuffer:async()=>bytes}))$('examples').value=example.path;}catch(e){if(loadingGeneration===generation){clearSelection();showStatus(e.message);}}}
$('examples').onchange=()=>openExample($('examples').value);
$('preserve-splines').checked=true;updateInputControls();updatePreservation();updateTolerance();updateCadSourceNote();
if(examples.some(x=>x.path==='examples/ifccad/overview.ifcx'))openExample('examples/ifccad/overview.ifcx');
