import {translate} from './i18n.mjs';
import {ifcxNodeJson} from './presentation-json.mjs';
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function itemTitle(node,language){return node.type==='drawing'?translate(language,'drawing')+(node.key==='drawing'?'':' · '+node.title):node.type==='group'||node.type==='file'?translate(language,node.title):['node','layer','layers','layout','linePattern','linePatterns','blockDefinition','blockDefinitions','table','stream'].includes(node.type)?node.title:translate(language,node.type)+' · '+node.title;}
export function renderInspection(model,state){
 const chevron='<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M5.5 3 L10.5 8 L5.5 13"/></svg>';
 const {language,selection,expanded,inspector,field=[],limit=150}=state,t=(k,v)=>translate(language,k,v),e=escapeHtml;
 const summary=value=>value===null?'null':Array.isArray(value)?(value.length<=4&&value.every(v=>typeof v!=='object')?'['+value.map(v=>e(v)).join(', ')+']':t('items',{count:value.length})):typeof value==='object'?t('fields',{count:Object.keys(value).length}):typeof value==='boolean'?t(value?'yes':'no'):e(value);
 const keyLabel=key=>t(key.replace(/^ifccad::geom::|^ifccad::/,''));
 const jump=(key,label)=>'<button class="reference" data-select="'+e(key)+'">'+e(label)+' ↗</button>';
 let shown=0;const roots=state.view==='nodes'?model.nodeRoots:state.view==='storage'?model.storageRoots:model.roots;
 const displayChildren=n=>state.view==='drawing'&&state.grouping!=='order'?(n.groupedChildren||n.children):n.children;
 function fields(value,path=[],depth=0,owner=''){if(value===null||typeof value!=='object'||depth>16)return '';return Object.entries(value).slice(0,100).map(([key,v])=>{const next=[...path,key],attribute=e(JSON.stringify(next)),fieldId=JSON.stringify([owner,next]),selected=owner===selection&&JSON.stringify(next)===JSON.stringify(field),button='<button class="property-choice'+(selected?' selected':'')+'" data-field="'+attribute+'"'+(selected?' aria-current="true"':'')+'>'+e(keyLabel(key))+'</button>';return v!==null&&typeof v==='object'?'<details class="tree-field" data-field-id="'+e(fieldId)+'"'+(state.fieldExpanded?.has(fieldId)?' open':'')+'><summary>'+button+' <span class="tree-value">'+summary(v)+'</span></summary>'+fields(v,next,depth+1,owner)+'</details>':'<div class="tree-field">'+button+' <span class="tree-value">'+summary(v)+'</span></div>';}).join('')+(Object.keys(value).length>100?'<div class="secondary">'+e(t('items',{count:Object.keys(value).length}))+' · JSON</div>':'');}
 function tree(keys,seen=new Set()){return keys.map(key=>{const n=model.nodes.get(key);if(!n||shown++>=limit)return '';const children=displayChildren(n).length||Object.keys(n.values||{}).length,open=expanded.has(key),cycle=seen.has(key);return '<div><div class="tree-row'+(key===selection&&field.length===0?' selected':'')+'">'+(children&&!cycle?'<button class="tree-expand" data-toggle="'+e(key)+'" aria-expanded="'+open+'" aria-label="'+e(itemTitle(n,language))+'">'+chevron+'</button>':'<span class="tree-expand"></span>')+'<button class="tree-item" data-select="'+e(key)+'"'+(key===selection&&field.length===0?' aria-current="true"':'')+'><span>'+e(itemTitle(n,language))+'</span>'+(n.type==='group'?'<span class="group-count">'+n.children.length+'</span>':'')+'</button></div>'+(open&&!cycle?'<div class="tree-children">'+tree(displayChildren(n),new Set([...seen,key]))+(n.type!=='group'&&(n.children.length===0||n.type==='stream')?'<div data-field-owner="'+e(key)+'">'+fields(n.values,[],0,key)+'</div>':'')+'</div>':'')+'</div>';}).join('');}
 const treeHtml=tree(roots),node=model.nodes.get(selection);if(!node)return {tree:treeHtml,details:'<p class="secondary">'+e(t('noSelection'))+'</p>',more:shown>limit};
 let value=node.values;for(const key of field)value=value?.[key];const heading='<h2>'+e(field.length?keyLabel(field.at(-1)):itemTitle(node,language))+'</h2>'+(field.length?'<p class="secondary">'+e(itemTitle(node,language))+'</p>':'')+'<div class="identity">'+e(node.key)+(field.length?' / '+e(field.join('/')):'')+'</div>';
 let details=heading;
 if(node.drawPosition!=null)details+='<p class="secondary">'+e(t('drawPosition'))+': '+(node.drawPosition+1)+'</p>';
 if(inspector==='relations'){
  for(const [title,edges]of [['outgoing',node.outgoing],['incoming',node.incoming]])details+='<h3>'+e(t(title))+'</h3><dl class="properties-list">'+(edges.length?edges.map(link=>{const key=title==='outgoing'?link.target:link.source;return '<div><dt>'+e(link.field)+'</dt><dd>'+(model.nodes.has(key)?jump(key,itemTitle(model.nodes.get(key),language)):e(key)+' · '+e(t('unresolved')))+'</dd></div>';}).join(''):'<p class="secondary">'+e(t('noRelations'))+'</p>')+'</dl>';
 }else if(inspector==='source'){
  if(model.format==='ifccad'&&node.raw){details+='<p class="secondary">'+e(t('compositionHelp'))+'</p><details open><summary>'+e(t('effectiveNode'))+'</summary><pre>'+e(ifcxNodeJson(node.raw))+'</pre></details>';for(const f of node.fragments)details+='<details><summary>'+e(t('fragment',{index:f.index}))+' · data['+f.index+']</summary><pre>'+e(JSON.stringify(f.value,null,2))+'</pre></details>';}
  else details+='<h3>'+e(t(['stream','table'].includes(node.type)?'storageJson':'inspectionJson'))+'</h3><pre>'+e(JSON.stringify(value,null,2))+'</pre>';
 }else{
 const help=t('help.'+node.type);if(!help.startsWith('help.'))details+='<p class="secondary">'+e(help)+'</p>';
  const assessment=node.values.boundsAssessment;if(assessment)details+='<p class="secondary">'+e(t('boundsSummary',{quality:t(assessment.quality||'empty'),proof:t(assessment.enclosureVerified?'enclosureChecked':'enclosureNotChecked')}))+'</p>';
  details+=node.type==='group'?'<p class="secondary">'+e(t('group'))+'</p>':'<h3>'+e(t('storedValues'))+'</h3>';
  const props=v=>v!==null&&typeof v==='object'?Object.entries(v):[['value',v]];
  details+='<dl class="properties-list">'+props(value).slice(0,100).map(([key,v])=>{const label=e(keyLabel(key)),edge=node.outgoing.find(l=>l.field.endsWith('.'+key)||l.field===key);if(edge&&model.nodes.has(edge.target))return '<div><dt>'+label+'</dt><dd>'+jump(edge.target,itemTitle(model.nodes.get(edge.target),language))+'</dd></div>';if(v!==null&&typeof v==='object')return '<div class="property-composite"><dt class="visually-hidden">'+label+'</dt><dd><details class="value-details"><summary><span class="property-label">'+label+'</span><span class="value-summary">'+chevron+'<span>'+summary(v)+'</span></span></summary><pre>'+e(JSON.stringify(v,null,2).slice(0,100000))+'</pre></details></dd></div>';return '<div><dt>'+label+'</dt><dd>'+summary(v)+'</dd></div>';}).join('')+'</dl>';
 }
 if(node.storage){const s=node.storage;details+='<h3>'+e(t('storageLocation'))+'</h3><dl class="properties-list"><div><dt>Stream</dt><dd>'+jump('stream:'+s.stream,s.stream)+'</dd></div><div><dt>'+e(t('row'))+'</dt><dd>'+s.row+'</dd></div>'+(s.offset!==undefined?'<div><dt>'+e(t('range'))+'</dt><dd>'+s.offset+' / '+s.count+'</dd></div>':'')+'</dl>';}
 return {tree:treeHtml,details,more:shown>limit};
}
