import {loadPreferences,savePreferences} from './preferences.mjs';
import {translate,localize} from './i18n.mjs';
import {createInspection} from './inspection-model.mjs';
import {renderInspection,itemTitle,escapeHtml} from './inspection-view.mjs';
import {initializeDialogs} from './dialogs.mjs';
import {inspectionReport} from './inspection-report.mjs';
export function initializeWorkspace({onTab=()=>{},onPreferences=()=>{}}={}){
 const $=id=>document.getElementById(id);let storage;try{storage=localStorage;}catch{}
 const preferences=loadPreferences(storage,navigator.language,matchMedia('(prefers-color-scheme: dark)').matches);
 const state={language:preferences.language,theme:preferences.theme,tab:'contents',view:'drawing',grouping:'type',selection:null,field:[],expanded:new Set(),fieldExpanded:new Set(),inspector:'properties',mode:'readable',limit:150,jsonScope:null,jsonField:[],statusSpec:{key:'select'}};let model,result,cadReport;
 const t=(key,values)=>translate(state.language,key,values);let loading,cadStatus;
 function renderCadStatus(){const phase=cadStatus?.phase,label=phase==='ready'?t('roundtripReady'):phase==='failed'?t('roundtripFailed'):phase?t(phase):'',text=phase?t('roundtripStatus',{format:cadStatus.format.toUpperCase(),version:cadStatus.version,status:label}):'';$('cad-roundtrip-status').textContent=text;$('cad-roundtrip-summary').textContent=text;$('cad-roundtrip-summary').hidden=!text;$('cad-roundtrip-state').hidden=!text;$('cad-roundtrip-status').title=cadStatus?.error||'';$('cad-roundtrip-cancel').hidden=!phase||['ready','failed','cancelled'].includes(phase);}
 function renderLoading(){const panel=$('loading-panel');panel.hidden=!loading;document.querySelectorAll('.workspace-body>section').forEach(section=>section.setAttribute('aria-busy',!!loading));if(loading){$('loading-name').textContent=loading.name;$('loading-action').textContent=t(loading.action,loading);$('loading-phase').textContent=t(loading.phase);}}
 function render(){
  $('content-tree').querySelectorAll('details[data-field-id]').forEach(d=>d.open?state.fieldExpanded.add(d.dataset.fieldId):state.fieldExpanded.delete(d.dataset.fieldId));
  document.documentElement.lang=state.language;document.documentElement.dataset.theme=state.theme;localize(document,state.language);$('language').value=state.language;$('theme').value=state.theme;
  $('application').dataset.workspace=state.tab;
  $('name').textContent=result?.source?.name||t('select');$('status').textContent=state.statusSpec.message||t(state.statusSpec.key,state.statusSpec.values);
  for(const name of ['contents','conversion','drawing']){$(name+'-panel').hidden=state.tab!==name;$(name+'-tab').setAttribute('aria-selected',state.tab===name);}
  const format=model?.format==='ocdraw'?'OCDraw':'IFCCAD';$('contents-tab').textContent=format+'-'+t('contents').toLowerCase();$('content-title').textContent=$('contents-tab').textContent;$('export').textContent=t('downloadNative',{format});
  for(const name of ['properties','relations','source'])$(name+'-tab').setAttribute('aria-selected',state.inspector===name);$('item-information').setAttribute('aria-labelledby',state.inspector+'-tab');
  $('structure').options[1].value=model?.format==='ocdraw'?'storage':'nodes';$('structure').options[1].textContent=t(model?.format==='ocdraw'?'storage':'nodes');$('structure').value=state.view;
  $('grouping-control').hidden=state.view!=='drawing'||state.mode==='json';$('grouping').value=state.grouping;
  $('empty-contents').hidden=!!model;$('content-tree').hidden=state.mode!=='readable';$('records').hidden=state.mode!=='json';$('readable-view').setAttribute('aria-pressed',state.mode==='readable');$('json-view').setAttribute('aria-pressed',state.mode==='json');
  if(model){const rendered=renderInspection(model,state);$('content-tree').innerHTML=rendered.tree;$('item-information').innerHTML=rendered.details;$('tree-more').hidden=!rendered.more||state.mode!=='readable';const n=model.nodes.get(state.selection);let json=model.sourceText;if(state.jsonScope){const selected=model.nodes.get(state.jsonScope);let v=selected?.raw||selected?.values;if(state.jsonField?.length){v=selected?.values;for(const k of state.jsonField)v=v?.[k];}json=JSON.stringify(v,null,2);}$('records').textContent=(json||'').slice(0,2*1024*1024);$('tree-heading').textContent=state.mode==='json'?t(state.jsonScope?'scopedJson':'fileJson'):t('structure');$('selection-status').textContent=n?t('selection',{name:itemTitle(n,state.language)}):'';$('unit-status').textContent=t('unitLabel',{unit:result.presentation?.unit||result.presentation?.graph?.data?.find(n=>n.attributes?.['ifccad::drawing'])?.attributes['ifccad::drawing'].lengthUnit||'—'});$('document-format').textContent=format;$('document-validity').textContent=t(model.valid?'strictValid':'invalid');}
  renderReport();renderLoading();renderCadStatus();
 }
 function renderReport(){const report=inspectionReport(result,cadReport);document.getElementById('report').textContent=JSON.stringify(report,null,2);const target=$('readable-report');target.replaceChildren();for(const [key,part]of [['reading',report.reader],['validation',report.validation],['conversion',report.conversion],['export',report.export],['failure',report.failure]]){const section=document.createElement('section');section.className='report-section';const h=document.createElement('h3');h.textContent=t(key);section.append(h);if(!part){const p=document.createElement('p');p.textContent=t('notRun');p.className='secondary';section.append(p);}else{const messages=part.messages||part.diagnostics||[];const p=document.createElement('p');p.textContent=part.message||part.status|| (key==='validation'?t(part.strictAvailable?'strictValid':'invalid'):part.format||'');section.append(p);if(messages.length){const ul=document.createElement('ul');for(const message of messages.slice(0,500)){const li=document.createElement('li');li.textContent=typeof message==='string'?message:[message.code,message.location,message.message,message.action,...(message.reasons||[])].filter(Boolean).join(' · ');ul.append(li);}section.append(ul);}if(part.text?.entries?.some(e=>e.glyphCoverage==='unassessed')){const notice=document.createElement('p');notice.className='secondary';notice.textContent=t('textGlyphNotice');section.append(notice);}if(part.geometry||part.geometryAssessment||part.text){const pre=document.createElement('pre');pre.textContent=JSON.stringify(part.text?{geometry:part.geometry||part.geometryAssessment,text:part.text}:part.geometry||part.geometryAssessment,null,2);section.append(pre);}}target.append(section);}}
 function select(key,field=[]){if(!model?.nodes.has(key))return;state.selection=key;state.field=field;function find(keys,path=[],seen=new Set()){for(const k of keys){if(k===key)return path;if(seen.has(k))continue;const found=find((state.view==='drawing'&&state.grouping!=='order'?model.nodes.get(k)?.groupedChildren:undefined)||model.nodes.get(k)?.children||[],[...path,k],new Set([...seen,k]));if(found)return found;}return null;}for(const k of find(state.view==='nodes'?model.nodeRoots:state.view==='storage'?model.storageRoots:model.roots)||[])state.expanded.add(k);render();$('content-tree').querySelector('[aria-current=true]')?.scrollIntoView({block:'nearest'});}
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();onTab(state.tab);});
 document.querySelectorAll('[data-inspector]').forEach(b=>b.onclick=()=>{state.inspector=b.dataset.inspector;render();});
 $('structure').onchange=e=>{state.view=e.target.value;state.limit=150;render();};$('readable-view').onclick=()=>{state.mode='readable';render();};$('json-view').onclick=()=>{state.mode='json';state.jsonScope=null;render();};$('scoped-json').onclick=()=>{state.mode='json';state.jsonScope=state.selection;state.jsonField=[...state.field];render();};$('tree-more').onclick=()=>{state.limit+=150;render();};
 $('grouping').onchange=e=>{state.grouping=e.target.value;render();};
 $('drawing').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.select)select(b.dataset.select);if(b.dataset.toggle){state.expanded.has(b.dataset.toggle)?state.expanded.delete(b.dataset.toggle):state.expanded.add(b.dataset.toggle);render();}if(b.dataset.field){event.preventDefault();select(b.closest('[data-field-owner]').dataset.fieldOwner,JSON.parse(b.dataset.field));}});
 for(const name of ['language','theme'])$(name).onchange=e=>{state[name]=e.target.value;savePreferences(storage,{language:state.language,theme:state.theme});render();onPreferences({language:state.language,theme:state.theme});};
 initializeDialogs();const handle=document.querySelector('.resize-handle');let width=350;
 const resize=w=>{width=Math.max(240,Math.min(520,w));document.documentElement.style.setProperty('--info-width',width+'px');};handle.addEventListener('pointerdown',event=>{handle.setPointerCapture(event.pointerId);});handle.addEventListener('pointermove',event=>{if(handle.hasPointerCapture(event.pointerId))resize(document.getElementById('drawing').getBoundingClientRect().right-event.clientX);});handle.addEventListener('pointerup',event=>handle.releasePointerCapture(event.pointerId));handle.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();resize(width+(e.key==='ArrowLeft'?20:-20));}});
 render();return {state,t,setCadStatus(value){cadStatus=value;renderCadStatus();},setLoading(value){loading={...loading,...value};renderLoading();},clearLoading(){loading=null;renderLoading();},setCadReport(value){cadReport=value;renderReport();},show(value,sourceText){cadReport=null;result=value;state.statusSpec=value.failure?{message:value.failure.message}:{key:value.validation?.strictAvailable?'ready':'invalid'};model=createInspection(value,sourceText);if(!model.nodes.has(state.selection)){state.selection=model.roots[0]||null;state.field=[];state.expanded=new Set(Array.from(model.nodes.values()).filter(n=>n.type==='layout'&&(n.values.kind==='model'||n.values['ifccad::layout']?.kind==='Model')||n.key==='group:layout'||n.key==='group:layouts').map(n=>n.key));state.view='drawing';state.mode='readable';state.jsonScope=null;}render();},clear(){model=null;result=null;cadReport=null;cadStatus=null;state.selection=null;state.expanded.clear();state.fieldExpanded.clear();$('selection-status').textContent='';$('unit-status').textContent='';$('document-format').textContent='';$('document-validity').textContent='';render();},selectTab(name){state.tab=name;render();onTab(name);},refresh:render,setStatus(key,values){state.statusSpec={key,values};$('status').textContent=t(key,values);}};
}
