pub(crate) const IFCCAD_PACKAGE_CHECKSUM_MISMATCH: &str = "IFCCAD_PACKAGE_CHECKSUM_MISMATCH";
pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_MISSING: &str = "IFCCAD_PACKAGE_ENTRYPOINT_MISSING";
pub(crate) const IFCCAD_PACKAGE_ENTRYPOINT_INVALID: &str = "IFCCAD_PACKAGE_ENTRYPOINT_INVALID";
pub(crate) const IFCCAD_PACKAGE_JSON_INVALID: &str = "IFCCAD_PACKAGE_JSON_INVALID";
pub(crate) const IFCCAD_PACKAGE_NODE_PATH_DUPLICATE: &str = "IFCCAD_PACKAGE_NODE_PATH_DUPLICATE";
pub(crate) const IFCCAD_PACKAGE_NODE_REFERENCE_MISSING: &str =
    "IFCCAD_PACKAGE_NODE_REFERENCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_NODE_REFERENCE_TYPE_MISMATCH: &str =
    "IFCCAD_PACKAGE_NODE_REFERENCE_TYPE_MISMATCH";
pub(crate) const IFCCAD_PACKAGE_PATH_INVALID: &str = "IFCCAD_PACKAGE_PATH_INVALID";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_MISSING: &str = "IFCCAD_PACKAGE_RESOURCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_ID_DUPLICATE: &str =
    "IFCCAD_PACKAGE_RESOURCE_ID_DUPLICATE";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_ID_MISMATCH: &str = "IFCCAD_PACKAGE_RESOURCE_ID_MISMATCH";
pub(crate) const IFCCAD_PACKAGE_TARGET_RESOURCE_MISSING: &str =
    "IFCCAD_PACKAGE_TARGET_RESOURCE_MISSING";
pub(crate) const IFCCAD_PACKAGE_SCHEMA_INVALID: &str = "IFCCAD_PACKAGE_SCHEMA_INVALID";
pub(crate) const IFCCAD_PACKAGE_TIMESTAMP_INVALID: &str = "IFCCAD_PACKAGE_TIMESTAMP_INVALID";
pub(crate) const IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED: &str =
    "IFCCAD_PACKAGE_RESOURCE_LIMIT_EXCEEDED";
pub(crate) const IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED: &str = "IFCCAD_PACKAGE_TOTAL_LIMIT_EXCEEDED";
pub(crate) const IFCCAD_PACKAGE_BINDING_INVALID: &str = "IFCCAD_PACKAGE_BINDING_INVALID";
pub(crate) const IFCCAD_PACKAGE_APPEARANCE_INVALID: &str = "IFCCAD_PACKAGE_APPEARANCE_INVALID";
pub(crate) const IFCCAD_PACKAGE_LAYER_NAME_DUPLICATE: &str = "IFCCAD_PACKAGE_LAYER_NAME_DUPLICATE";
