use super::projection;
use super::Result;
use ifccad_convert::{
    cad_document_to_ifccad_document, ifccad_document_to_cad_document, CadToIfccadOptions,
    IfccadLossPolicy, IfccadToCadOptions,
};
use ocdraw::ifccad::{encode_ifccad_document, load_ifccad_bytes};
use ocdraw::ocdraw::{encode_ocdraw_document, load_ocdraw_bytes};
use ocdraw_convert::opencadcodec::{
    CadDocument, DwgReader, DwgWriter, DxfReader, DxfVersion, DxfWriter,
};
use ocdraw_convert::{
    cad_document_to_ocdraw_document, ocdraw_document_to_cad_document, CadToOcdrawOptions,
    OcdrawLossPolicy, OcdrawToCadOptions,
};
use serde_json::{json, Value};
use std::path::Path;
use std::{fs, io::Cursor};
pub struct Prepared {
    pub document: CadDocument,
    pub expected: Value,
    pub evidence: Value,
}
fn canonical_diagnostics(mut values: Vec<Value>) -> Vec<Value> {
    // CAD object inventory uses a hash map; diagnostic order has no meaning.
    // Retain complete messages and duplicates in a deterministic order.
    values.sort_by_cached_key(Value::to_string);
    values
}
fn ifcx_options(allow: bool) -> CadToIfccadOptions {
    CadToIfccadOptions {
        loss_policy: if allow {
            IfccadLossPolicy::Allow
        } else {
            IfccadLossPolicy::Reject
        },
        ..Default::default()
    }
}
fn ifcx_import_options(allow: bool) -> IfccadToCadOptions {
    IfccadToCadOptions {
        loss_policy: ifcx_options(allow).loss_policy,
        ..Default::default()
    }
}
fn export_options(allow: bool) -> CadToOcdrawOptions {
    CadToOcdrawOptions {
        loss_policy: if allow {
            OcdrawLossPolicy::Allow
        } else {
            OcdrawLossPolicy::Reject
        },
        ..Default::default()
    }
}
fn import_options(allow: bool) -> OcdrawToCadOptions {
    OcdrawToCadOptions {
        loss_policy: if allow {
            OcdrawLossPolicy::Allow
        } else {
            OcdrawLossPolicy::Reject
        },
        ..Default::default()
    }
}
fn fix(cad: &mut CadDocument) {
    cad.version = DxfVersion::AC1032;
    cad.header.create_date_julian = 0.;
    cad.header.update_date_julian = 0.;
    cad.header.total_editing_time = 0.;
    cad.header.user_elapsed_time = 0.;
}
fn restore_runtime_scaffold(cad: &mut CadDocument) -> Result<Value> {
    // OCDraw import leaves table handles unset; names carry the layer meaning.
    let missing = cad
        .layers
        .iter()
        .filter(|l| l.handle.is_null())
        .map(|l| l.name.clone())
        .collect::<Vec<_>>();
    for name in &missing {
        let handle = cad.allocate_handle();
        cad.layers.get_mut(name).unwrap().handle = handle;
    }
    let fresh = CadDocument::new();
    // These are generated by OCDraw import from unit/model metadata, not
    // authored paper content. Restore the codec's empty runtime scaffold.
    let measurement = cad.header.measurement;
    cad.header.measurement = fresh.header.measurement;
    let paper = cad.header.paper_space_block_handle;
    let template = fresh
        .objects
        .values()
        .find_map(|o| match o {
            ocdraw_convert::opencadcodec::objects::ObjectType::Layout(l)
                if l.block_record == fresh.header.paper_space_block_handle =>
            {
                Some(l)
            }
            _ => None,
        })
        .unwrap();
    let restored_paper = !cad.objects.contains_key(&template.handle);
    if restored_paper {
        let record = cad
            .block_records
            .iter_mut()
            .find(|r| r.handle == paper)
            .ok_or("missing reserved paper block")?;
        if !record.entity_handles.is_empty() || !record.layout.is_null() {
            return Err("cannot restore nonempty paper scaffold".into());
        }
        record.layout = template.handle;
        let mut layout = template.clone();
        layout.block_record = paper;
        cad.objects.insert(
            layout.handle,
            ocdraw_convert::opencadcodec::objects::ObjectType::Layout(layout),
        );
        let Some(ocdraw_convert::opencadcodec::objects::ObjectType::Dictionary(dict)) =
            cad.objects.get_mut(&cad.header.acad_layout_dict_handle)
        else {
            return Err("missing layout dictionary".into());
        };
        dict.add_entry("Layout1", template.handle);
    }
    Ok(
        json!({"allocatedLayerNames":missing,"measurementBefore":measurement,"measurementAfter":cad.header.measurement,"restoredEmptyLayout1":restored_paper}),
    )
}
pub fn inventory(cad: &CadDocument) -> Value {
    let mut kinds = std::collections::BTreeMap::<String, usize>::new();
    for entity in cad.entities() {
        *kinds
            .entry(entity.as_entity().entity_type().into())
            .or_default() += 1;
    }
    json!({"entityKinds":kinds,"layers":cad.layers.len(),"blockRecords":cad.block_records.len(),"patterns":cad.line_types.len()})
}
pub fn prepare(source: &CadDocument, allow: bool) -> Result<Prepared> {
    let o = cad_document_to_ocdraw_document(source, export_options(allow))?;
    let o_diag = o
        .diagnostics()
        .iter()
        .map(|d| json!({"loss":d.is_loss(),"detail":format!("{d:?}")}))
        .collect::<Vec<_>>();
    let c = ocdraw_document_to_cad_document(o.document(), import_options(allow))?;
    let c_diag = c
        .diagnostics()
        .iter()
        .map(|d| json!({"code":d.code,"location":d.location,"message":d.message}))
        .collect::<Vec<_>>();
    if !allow && (!o_diag.is_empty() || !c_diag.is_empty()) {
        return Err("synthetic preparation contains OCDraw diagnostics".into());
    }
    let mut intermediate = c.document().clone();
    let allocated = restore_runtime_scaffold(&mut intermediate)?;
    let i = cad_document_to_ifccad_document(
        &intermediate,
        projection::metadata(),
        ifcx_options(allow),
    )?;
    let i_diag=i.diagnostics().iter().map(|d|json!({"code":d.code,"location":d.location,"message":d.message,"action":format!("{:?}",d.action),"loss":d.is_loss()})).collect::<Vec<_>>();
    let back = ifccad_document_to_cad_document(i.document(), ifcx_import_options(false))?;
    if !allow && i.diagnostics().iter().any(|d| d.is_loss()) {
        return Err("synthetic preparation contains IFCX loss".into());
    }
    if back.diagnostics().iter().any(|d| d.is_loss()) {
        return Err("new loss when reconstructing candidate".into());
    }
    let mut document = back.into_document();
    fix(&mut document);
    let expected = projection::snapshot(&document)?;
    if !allow {
        let before = projection::snapshot(source)?;
        require_equal(&before, &expected)?;
    }
    let evidence = json!({"sourceInventory":inventory(source),"retainedInventory":inventory(&document),"stages":[{"name":"CAD to OCDrawDocument","diagnostics":canonical_diagnostics(o_diag),"geometry":format!("{:?}",o.geometry_assessment())},{"name":"OCDrawDocument to CAD","diagnostics":canonical_diagnostics(c_diag),"geometry":format!("{:?}",c.geometry_assessment())},{"name":"CAD to IfccadDocument","diagnostics":canonical_diagnostics(i_diag)}],"normalization":[]});
    let mut evidence = evidence;
    evidence["runtimeScaffoldBridge"] = allocated;
    Ok(Prepared {
        document,
        expected,
        evidence,
    })
}
fn require_equal(a: &Value, b: &Value) -> Result<()> {
    let differences = projection::differences(a, b);
    if differences.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "semantic mismatch: {}",
            serde_json::to_string(&differences)?
        )
        .into())
    }
}
pub fn read_cad(bytes: &[u8], format: &str) -> Result<CadDocument> {
    match format {
        "dxf" => Ok(DxfReader::from_reader(Cursor::new(bytes.to_vec()))?.read()?),
        "dwg" => Ok(DwgReader::from_stream(Cursor::new(bytes.to_vec())).read()?),
        _ => Err("unknown CAD format".into()),
    }
}
fn write_cad(cad: &CadDocument, format: &str) -> Result<Vec<u8>> {
    match format {
        "dxf" => Ok(DxfWriter::new(cad).write_to_vec()?),
        "dwg" => Ok(DwgWriter::write_to_vec(cad)?),
        _ => Err("unknown CAD format".into()),
    }
}
pub fn stabilize(mut p: Prepared) -> Result<Prepared> {
    stabilize_with_limit(&mut p, 3)?;
    Ok(p)
}
fn stabilize_with_limit(p: &mut Prepared, limit: usize) -> Result<()> {
    let mut rounds = vec![];
    for round in 0..=limit {
        let dxf = read_cad(&write_cad(&p.document, "dxf")?, "dxf")?;
        let dwg = read_cad(&write_cad(&p.document, "dwg")?, "dwg")?;
        let dx = projection::snapshot(&dxf)?;
        let dw = projection::snapshot(&dwg)?;
        let diffs = projection::differences(&p.expected, &dx);
        let dw_diffs = projection::differences(&p.expected, &dw);
        if diffs.is_empty() && dw_diffs.is_empty() {
            p.evidence["normalization"] = json!(rounds);
            return Ok(());
        }
        if diffs.iter().chain(&dw_diffs).any(|d| d["numeric"] != true) {
            return Err(format!(
                "nonnumerical normalization change: {}",
                json!({"dxf":diffs,"dwg":dw_diffs})
            )
            .into());
        }
        if round == limit {
            return Err(format!(
                "no exact common fixed point after {limit} rounds: {}",
                json!({"rounds":rounds,"dxf":diffs,"dwg":dw_diffs})
            )
            .into());
        }
        let physical = read_cad(&write_cad(&dxf, "dwg")?, "dwg")?;
        let logical = cad_document_to_ifccad_document(
            &physical,
            projection::metadata(),
            ifcx_options(false),
        )?;
        let next = ifccad_document_to_cad_document(logical.document(), ifcx_import_options(false))?;
        let mut document = next.into_document();
        fix(&mut document);
        let snapshot = projection::snapshot(&document)?;
        let change = projection::differences(&p.expected, &snapshot);
        if change.iter().any(|d| d["numeric"] != true) {
            return Err(format!("nonnumerical candidate change: {}", json!(change)).into());
        }
        rounds.push(json!({"round":round+1,"dxfDifferences":diffs,"dwgDifferences":dw_diffs,"candidateDifferences":change}));
        p.document = document;
        p.expected = snapshot;
    }
    unreachable!()
}
pub fn generate(p: &Prepared, output: &Path) -> Result<Value> {
    if fs::read_dir(output)?.next().is_some() {
        return Err("case output must be empty".into());
    }
    require_equal(&p.expected, &projection::snapshot(&p.document)?)?;
    fs::write(
        output.join("expected.json"),
        serde_json::to_vec_pretty(&p.expected)?,
    )?;
    fs::write(
        output.join("preparation.json"),
        serde_json::to_vec_pretty(&p.evidence)?,
    )?;
    let o = cad_document_to_ocdraw_document(&p.document, export_options(false))?;
    if !o.diagnostics().is_empty() {
        return Err(format!("post-freeze OCDraw loss: {:?}", o.diagnostics()).into());
    }
    let i =
        cad_document_to_ifccad_document(&p.document, projection::metadata(), ifcx_options(false))?;
    fs::write(
        output.join("drawing.ocdraw.json"),
        encode_ocdraw_document(o.document())?.bytes(),
    )?;
    fs::write(
        output.join("drawing.ifcx"),
        encode_ifccad_document(i.document())
            .map_err(|e| format!("{e:?}"))?
            .bytes(),
    )?;
    fs::write(output.join("drawing.dxf"), write_cad(&p.document, "dxf")?)?;
    fs::write(output.join("drawing.dwg"), write_cad(&p.document, "dwg")?)?;
    verify(output)
}
pub fn verify(directory: &Path) -> Result<Value> {
    let expected: Value = serde_json::from_slice(&fs::read(directory.join("expected.json"))?)?;
    let mut artifacts = vec![];
    for (file, format) in [
        ("drawing.ocdraw.json", "ocdraw"),
        ("drawing.ifcx", "ifcx"),
        ("drawing.dxf", "dxf"),
        ("drawing.dwg", "dwg"),
        ("drawing.compact.ocdraw.json", "ocdraw"),
        ("drawing.compact.ifcx", "ifcx"),
    ] {
        if file.contains("compact") && !directory.join(file).exists() {
            continue;
        }
        let bytes = fs::read(directory.join(file))?;
        let cad = match format {
            "ocdraw" => {
                let drawing = load_ocdraw_bytes(&bytes)?;
                let out =
                    ocdraw_document_to_cad_document(drawing.document(), import_options(false))?;
                if !out.diagnostics().is_empty() {
                    return Err(format!(
                        "post-freeze OCDraw import diagnostics: {:?}",
                        out.diagnostics()
                    )
                    .into());
                }
                let mut cad = out.into_document();
                restore_runtime_scaffold(&mut cad)?;
                cad
            }
            "ifcx" => {
                let native =
                    load_ifccad_bytes(&bytes, Default::default()).map_err(|e| format!("{e:?}"))?;
                let out = ifccad_convert::ifccad_source_to_cad_document(
                    &native,
                    ifcx_import_options(false),
                )?;
                if out.diagnostics().iter().any(|d| d.is_loss()) {
                    return Err("post-freeze IFCX loss".into());
                }
                out.into_document()
            }
            _ => read_cad(&bytes, format)?,
        };
        let snapshot = projection::snapshot(&cad)?;
        require_equal(&expected, &snapshot)?;
        artifacts.push(json!({"file":file,"format":format,"bytes":bytes.len(),"readback":"exact"}));
    }
    Ok(
        json!({"status":"passed","artifacts":artifacts,"inventory":inventory(&read_cad(&fs::read(directory.join("drawing.dwg"))?,"dwg")?)}),
    )
}

#[cfg(test)]
mod tests {
    use super::super::corpus::{generate as recipe, Case};
    use super::*;
    #[test]
    fn diagnostics_have_stable_order_without_losing_duplicates() {
        let a = vec![
            json!({"code":"b","location":"two"}),
            json!({"code":"a","location":"one"}),
            json!({"code":"a","location":"one"}),
        ];
        let mut b = a.clone();
        b.reverse();
        assert_eq!(canonical_diagnostics(a), canonical_diagnostics(b));
        assert_eq!(
            canonical_diagnostics(vec![json!("same"), json!("same")]).len(),
            2
        );
    }
    fn fixture() -> CadDocument {
        recipe(&Case {
            id: "test".into(),
            family: "line".into(),
            count: 3,
        })
        .unwrap()
    }
    fn dir() -> std::path::PathBuf {
        let root = std::env::temp_dir().join(format!(
            "ocdraw-exchange-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir(&root).unwrap();
        root
    }
    #[test]
    fn four_actual_readbacks_equal_one_reference() {
        let root = dir();
        let p = prepare(&fixture(), false).unwrap();
        let result = generate(&p, &root).unwrap();
        assert_eq!(result["status"], "passed");
        assert_eq!(result["artifacts"].as_array().unwrap().len(), 4);
        assert_eq!(verify(&root).unwrap()["status"], "passed");
        std::fs::remove_dir_all(root).unwrap();
    }
    #[test]
    fn post_freeze_loss_fails_case() {
        let root = dir();
        let mut p = prepare(&fixture(), false).unwrap();
        p.document.header.project_name = "must not disappear".into();
        assert!(generate(&p, &root).is_err());
        std::fs::remove_dir_all(root).unwrap();
    }
    #[test]
    fn corrupted_native_or_cad_file_fails_verification() {
        let root = dir();
        let p = prepare(&fixture(), false).unwrap();
        generate(&p, &root).unwrap();
        std::fs::write(root.join("drawing.dwg"), b"not a drawing").unwrap();
        assert!(verify(&root).is_err());
        std::fs::remove_dir_all(root).unwrap();
    }
    #[test]
    fn preparation_cannot_hide_loss_in_a_synthetic_fixture() {
        let mut cad = fixture();
        cad.header.project_name = "authored source".into();
        assert!(prepare(&cad, false).is_err());
        assert!(prepare(&cad, true).is_ok());
    }
    #[test]
    fn source_aware_readback_rejects_foreign_graph() {
        let root = dir();
        generate(&prepare(&fixture(), false).unwrap(), &root).unwrap();
        let file = root.join("drawing.ifcx");
        let mut value: Value = serde_json::from_slice(&fs::read(&file).unwrap()).unwrap();
        value["data"]
            .as_array_mut()
            .unwrap()
            .push(json!({"path":"foreign","attributes":{"example::note":"retained"}}));
        fs::write(file, serde_json::to_vec(&value).unwrap()).unwrap();
        assert!(verify(&root).is_err());
        fs::remove_dir_all(root).unwrap();
    }
    #[test]
    fn normalization_respects_round_limit_and_records_numeric_changes() {
        let cad = recipe(&Case {
            id: "angle".into(),
            family: "blocks".into(),
            count: 3,
        })
        .unwrap();
        let mut p = prepare(&cad, false).unwrap();
        let native = cad_document_to_ifccad_document(
            &p.document,
            projection::metadata(),
            ifcx_options(false),
        )
        .unwrap();
        let mut doc = native.document().clone();
        let ocdraw::ifccad::IfccadEntityKind::BlockInstance { transform, .. } =
            &mut doc.model.entities[0].as_native_mut().unwrap().kind
        else {
            panic!()
        };
        transform.rotation = 1.570796326794893;
        ocdraw::ifccad::recompute_ifccad_document_bounds(&mut doc).unwrap();
        p.document = ifccad_document_to_cad_document(&doc, ifcx_import_options(false))
            .unwrap()
            .into_document();
        fix(&mut p.document);
        p.expected = projection::snapshot(&p.document).unwrap();
        let mut blocked = Prepared {
            document: p.document.clone(),
            expected: p.expected.clone(),
            evidence: p.evidence.clone(),
        };
        assert!(stabilize_with_limit(&mut blocked, 0)
            .unwrap_err()
            .to_string()
            .contains("after 0 rounds"));
        let stable = stabilize(p).unwrap();
        assert_eq!(
            stable.evidence["normalization"].as_array().unwrap().len(),
            2
        );
    }
}
