"""Regenerate the pinned Unicode 17 full-default case-fold table."""

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'schemas/ifcdr/unicode/CaseFolding-17.0.0.txt'
OUTPUT = ROOT / 'src/ifcdr/unicode_casefold_17.rs'
SHA256 = 'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = SOURCE.read_bytes()
    assert hashlib.sha256(data).hexdigest() == SHA256, 'Pinned Unicode data changed'
    mappings = {}
    for line in data.decode('utf-8').splitlines():
        fields = [part.strip() for part in line.split('#')[0].split(';')]
        if len(fields) < 3 or fields[1] not in ('C', 'F'):
            continue
        scalar = int(fields[0], 16)
        assert scalar not in mappings
        mappings[scalar] = ''.join('\\u{' + f'{int(cp, 16):x}' + '}'
                                   for cp in fields[2].split())
    lines = ['// Generated by scripts/generate_casefold.py; do not edit by hand.',
             '// Unicode 17.0.0 C/F data; license: schemas/ifcdr/unicode/LICENSE.txt.',
             '#[rustfmt::skip]',
             'pub(super) const CASE_FOLD: &[(char, &str)] = &[']
    lines += [f'    (\'\\u{{{scalar:x}}}\', "{mapping}"),'
              for scalar, mapping in sorted(mappings.items())]
    lines += ['];', '']
    rendered = '\n'.join(lines)
    if args.check:
        assert OUTPUT.read_text(encoding='utf-8') == rendered, 'Generated table differs'
    else:
        OUTPUT.write_text(rendered, encoding='utf-8', newline='\n')
    print(f"{'Verified' if args.check else 'Generated'} {len(mappings)} full-default mappings")


if __name__ == '__main__':
    main()
